# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
#    -   id: trailing-whitespace
#    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb=10240", "--enforce-all"]
    -   id: check-case-conflict
#    -   id: forbid-submodules
    -   id: check-merge-conflict
    -   id: forbid-new-submodules


-   repo: https://github.com/mxr/sync-pre-commit-deps
    rev: v0.0.1
    hooks:
    -   id: sync-pre-commit-deps

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck
        name: Check shell scripts with shellcheck
        types: [shell]
        args: ['--severity=warning']