# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
#    -   id: trailing-whitespace
#    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb=10240", "--enforce-all"]
    -   id: check-case-conflict
#    -   id: forbid-submodules
    -   id: check-merge-conflict
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        name: detect secrets