" 2024-06-30 
" Syntax Highlighting for Markdown
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown
syntax on
filetype on

" Spaces not Tabs
set tabstop=2
set shiftwidth=2
set expandtab

" Let Delete delete beyond the current insert session
set backspace=indent,eol,start
